### ISSUE TITLE
Search Results Columns aren't splitted

### ISSUE THREAD

**Issue by Nama** [reneeb/otrs-SplitFromSubjectColumn#2]
Hi,
I like this package and appreciate your work!
But the search results aren't splitted, could you please add this, too?

Sincerely

**Comment by reneeb** [comment]
Hi,

thanks for your report. You can activate the module for the search results as well: Go to Admin -> SysConfig -> SplitFromSubjectColumn -> Outputfilter. There you can add "AgentTicketSearch" as a key and "1" as a value. Just click the "+" button on the lower right...

Kind regards,
Renée
